apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: obs
data:
  filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
        - '/var/lib/docker/containers/*/*.log'

        processors:
        - add_cloud_metadata:

        processors:
        - add_kubernetes_metadata:
            in_cluster: true

      output.logstash:
        hosts: ['logstash-service:5044']
