apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  namespace: obs
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0"
    elasticsearch.hosts: [ "http://elasticsearch-logging:9200" ]
