apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: obs
  labels:
    k8s-app: kibana-logging
spec:
  type: NodePort
  ports:
  - port: 5601
  selector:
    k8s-app: kibana-logging

