apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-controller
  namespace: controller
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: master-controller
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: pod_ip
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: hostname
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node_name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
